version: 2

steps:
  - &install_equinox
    run:
        name: Install Equinox Release Tool
        command: |
          mkdir ~/download
          cd ~/download && curl -O https://bin.equinox.io/c/mBWdkfai63v/release-tool-stable-linux-amd64.zip
          sudo unzip ~/download/release-tool-stable-linux-amd64.zip -d /usr/local/bin

defaults: &defaults
  docker:
    - image: circleci/golang:1.12.4-node
      auth:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_TOKEN

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: go test -v -race ./...

  deploy_stable:
    <<: *defaults
    steps:
      - checkout
      - *install_equinox
      - run:
          name: Release to Stable Channel
          command: |
            echo -e $EQUINOX_KEY > equinox.key
            CGO_ENABLED=0 equinox release --version=${CIRCLE_TAG:1} --platforms="darwin_amd64 linux_amd64 darwin_386 linux_386 windows_amd64 windows_386" --signing-key=equinox.key --app=$EQUINOX_APP_ID --token=$EQUINOX_ACC_TOKEN --channel stable -- -ldflags "-X main.releaseChannel=stable -X main.build=${CIRCLE_SHA1:0:8}" github.com/rainforestapp/rainforest-cli
            equinox publish --token=$EQUINOX_ACC_TOKEN --app=$EQUINOX_APP_ID --channel beta --release=${CIRCLE_TAG:1}
            equinox publish --token=$EQUINOX_ACC_TOKEN --app=$EQUINOX_APP_ID --channel dev --release=${CIRCLE_TAG:1}
            rm -f equinox.key

  deploy_beta:
    <<: *defaults
    steps:
      - checkout
      - *install_equinox
      - run:
          name: Release to Beta Channel
          command: |
            echo -e $EQUINOX_KEY > equinox.key
            CGO_ENABLED=0 equinox release --version=${CIRCLE_TAG:1} --platforms="darwin_amd64 linux_amd64 darwin_386 linux_386 windows_amd64 windows_386" --signing-key=equinox.key --app=$EQUINOX_APP_ID --token=$EQUINOX_ACC_TOKEN --channel beta -- -ldflags "-X main.releaseChannel=beta -X main.build=${CIRCLE_SHA1:0:8}" github.com/rainforestapp/rainforest-cli
            equinox publish --token=$EQUINOX_ACC_TOKEN --app=$EQUINOX_APP_ID --channel dev --release=${CIRCLE_TAG:1}
            rm -f equinox.key

  deploy_dev:
    <<: *defaults
    steps:
      - checkout
      - *install_equinox
      - run:
          name: Release to Dev Channel
          command: |
            echo -e $EQUINOX_KEY > equinox.key
            CGO_ENABLED=0 equinox release --version=${CIRCLE_SHA1:0:8} --platforms="darwin_amd64 linux_amd64 darwin_386 linux_386 windows_amd64 windows_386" --signing-key=equinox.key --app=$EQUINOX_APP_ID --token=$EQUINOX_ACC_TOKEN --channel dev -- -ldflags "-X main.releaseChannel=dev -X main.build=${CIRCLE_SHA1:0:8}" github.com/rainforestapp/rainforest-cli
            rm -f equinox.key

  release:
    <<: *defaults
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | GITHUB_TOKEN=$(GITHUB_ACCESS_TOKEN) bash

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          context:
            - DockerHub
      - deploy_dev:
          requires:
            - test
          filters:
            branches:
              only: master
          context:
            - DockerHub
      - deploy_beta:
          filters:
            # don't execute on branch pushes, only tag pushes
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(\-(alpha|beta)\.[0-9]+)$/
          context:
            - DockerHub
      - deploy_stable:
          filters:
            # don't execute on branch pushes, only tag pushes
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
          context:
            - DockerHub
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
