version: 2.1
defaults: &defaults
  docker:
    - image: cimg/go:1.17.1-node

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: go test -v -race ./...

  release:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Release via GoReleaser
          command: |
            export GITHUB_TOKEN=$GITHUB_ACCESS_TOKEN
            curl -sL https://git.io/goreleaser | bash
      - run:
          name: Show checksums
          command: cat dist/checksums.txt
      - store_artifacts:
          path: dist/checksums.txt

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          context:
            - DockerHub
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
