on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build
        run: |
          cd chocolatey
          ruby main.rb
      -
        name: Choco Pack
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: pack
      -
        name: Choco Push
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: push @(gci chocolatey/rainforest-cli/*.nupkg)[0] --key $env:CHOCO_API_KEY --source https://push.chocolatey.org/
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
      - 
        name: Save Choco pacakge
        uses: actions/upload-artifact@v2
        with:
          name: rainforest-cli.package
          path: chocolatey/rainforest-cli/*.nupkg