on: push
jobs:
  chocolatey:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install deps
        run: |
          cd chocolatey
          gem install bundler
          bundle install
      -
        name: Build
        run: |
          cd chocolatey
          ruby main.rb
      -
        name: Choco Pack
        run: |
          cd chocolatey/rainforest-cli/
          choco pack
      -
        name: Choco Push
        run: |
          cd chocolatey/rainforest-cli/
          choco push @(gci *.nupkg)[0] --key $env:CHOCO_API_KEY --source https://push.chocolatey.org/
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
      - 
        name: Save Choco pacakge
        uses: actions/upload-artifact@v2
        with:
          name: rainforest-cli.package
          path: chocolatey/rainforest-cli/*.nupkg